4_flask_app_mio/flask_app/my_app/__init__.py
from flask import Flask, url_for, redirect
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user, logout_user
from functools import wraps

app = Flask(__name__)

app.config.from_object('configuration.DevelopmentConfig')
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.init_app(app)

login_manager.login_view = "fauth.login"


def role_admin_need(f):
    @wraps(f)
    def wrapper(*args, **kwds):
        if current_user.rol.value != 'admin':
            #Acá colocamos la funcionalidad necesaria para manejar
            #los permisos usando la fx unauthorized de la libreria login_manager
            logout_user()
            return redirect(url_for('fauth.login'))

        return f(*args, **kwds)
    return wrapper


from my_app.product.product import product
from my_app.product.category import category
#from my_app.auth.views import auth
from my_app.fauth.views import fauth

#Rest API
from my_app.rest_api.product_api import product_view

# Importar las vistas
app.register_blueprint(product)
app.register_blueprint(category)
#app.register_blueprint(auth)
app.register_blueprint(fauth)

db.create_all()


@app.template_filter('mydouble')
def mydouble_filter(n):
    if n:
        return n*2
    return "Dato no válido"

4_flask_app_mio/flask_app/my_app/fauth/views.py
from flask import Blueprint, session, render_template, flash, request, redirect, url_for
from werkzeug.exceptions import abort

from my_app.auth.model.user import User, LoginForm, RegisterForm
from my_app import db
from flask_login import login_user, logout_user, current_user, login_required
from my_app import login_manager

fauth = Blueprint('fauth', __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@fauth.route('/register', methods=('GET', 'POST'))
def register():
    form = RegisterForm(meta={'csrf': False})

    if form.validate_on_submit():

        if User.query.filter_by(username=form.username.data).first():
            flash('El usuario ya existe', 'danger')
        else:
            # Creamos el usuario
            p = User(form.username.data, form.password.data)
            db.session.add(p)
            db.session.commit()
            flash("Usuario creado con éxito")

        return redirect(url_for('auth.register'))

    return render_template('auth/register.html', form=form)


@fauth.route('/login', methods=('GET', 'POST'))
def login():
    if current_user.is_authenticated:
        flash("Ya estás autenticado")
        return redirect(url_for('product.index'))

    form = LoginForm(meta={'csrf': False})

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and User.check_password(user, form.password.data):
            # Registramos la sesión.
            login_user(user)
            flash("Bienvenido nuevamente " + user.username)

            next = request.form['next']
            # is_safe_url should check if the url is safe for redirects.
            # See http://flask.pocoo.org/snippets/62/ for an example.
            # if not is_safe_url(next):
            #     return abort(400)

            return redirect(next or url_for('product.index'))
        else:
            # Error de password
            flash('Usuario o Contraseña Incorrectos', 'danger')

    return render_template('auth/login.html', form=form)


@fauth.route('/logout')
def logout():
    # Se usa en este caso el método pop para eliminar
    # cada uno de los elementos de session
    logout_user()

    return redirect(url_for('fauth.login'))


@fauth.route('/protegido')
@login_required
def protegido():
    return "<h1>Vista protegida</h1>"

4_flask_app_mio/flask_app/my_app/rest_api/__init__.py
#Sin contenido
#Pero es necesario para crear un aplicación modular en python

4_flask_app_mio/flask_app/my_app/templates/category/_form.html
<div class="form-group">
    {{ form.name.label }} 
    {{ form.name(class="form-control", placeholder="Nombre Categoría") }}
</div>

4_flask_app_mio/flask_app/my_app/templates/category/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success fade show mt-3" id="alert-message">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

4_flask_app_mio/flask_app/my_app/templates/category/create.html
{% extends 'layout/base.html' %}

{% block container %}
    {% include 'category/_message.html' %}

    <form action="{{ url_for('category.create') }}" method="post">
        {% include 'category/_form.html' %}
        <input class="btn btn-success" type="submit" value="Enviar">
    </form>
    <br>
{% endblock %}

4_flask_app_mio/flask_app/my_app/templates/category/filter.html
<h3>{{product['name']}}</h3>

<p>{{product['category']}}</p>
<p>$ {{product['price']}}</p>

<p>{{product['price']|default('Sin precio', True)}}</p>

{{ "<h1>Filtro safe: Hola Mundo</h1>" | safe }}

<p>{{ "Filtro truncate: Esto es la descripcion de un producto bastante chulo" | truncate(33) }}</p>
<p>{{ "Filtro truncate: Esto es la descripcion de un producto bastante chulo" | count }}</p>
<p>Filtro float: {{70 | float}}</p>
<p>Filtro int: {{"70" | int}}</p>
<p>Filtro round: {{3.1415926535 | round(3) }}</p>
<p>Filtro join: {{["iPhone","iPad"] | join(", ")}}</p>
<p>Filtro length: {{["iPhone","iPad"] | length}}</p>
<p>{{ {'ofer': False, 'price' : 50.5, 'k' : 45} | tojson}}</p>

<p>Filtro gobal custom {{product['price'] | mydouble}}</p>

<p>Filtro local custom {{product | iva}}</p>

4_flask_app_mio/flask_app/my_app/templates/category/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}
    {% include 'category/_message.html' %}
    <br>
    <div>
        <a class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Agregar una categoría en la BD" href="{{ url_for('category.create') }}"><i class="fa fa-plus"></i> Agregar Categoría</a>
    </div>
    <br>
    <div class="list-category">
        {% for category in categories.items %}
            <div class="jumbotron pb-2 pt-3 {{ loop.cycle('odd', 'even') }}">
                <h3>
                    <a href="#">
                        {{category['name']}}
                    </a>
                </h3>
                <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar Producto" href="{{ url_for('category.update', id=category['id'])}}"><i class="fa fa-edit"></i></a>
                <button data-toggle="modal" data-target="#deleteModal" data-name="{{ category['name'] }}" data-id="{{ category['id'] }}" class="btn btn-danger btn-sm" href="{{ url_for('category.delete', id=category['id'])}}"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="Eliminar {{ category['name'] }}"></i></button>
            </div>
        {% endfor %}
    </div>

    {{ m_pagination(categories, 'category.index') }}
    
    <!-- Modal para confirmar la eliminación de los categoryos -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                ¿Seguro que desea borrar el registro seleccionado?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <a href="#" id="deleteProduct" class="btn btn-danger">Borrar</a>
            </div>
          </div>
        </div>
      </div>

    <script>
        window.onload = function(){
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') // Extract info from data-* attributes 
                var name = button.data('name') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title span').text(name)

                $("#deleteProduct").attr("href", "/category-delete/" + id)
            })
        }
    </script>
{% endblock %}

4_flask_app_mio/flask_app/my_app/templates/category/update.html
{% extends 'layout/base.html' %}

{% block container %}
    {% include 'category/_message.html' %}
    
    <form action="{{ url_for('category.update', id=category.id) }}" method="post">
        {% include 'category/_form.html' %}
        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>
    <br>
{% endblock %}

4_flask_app_mio/flask_app/my_app/templates/fragment/_footer.html
<footer class="bg-dark text-center text-lg-start">
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(167, 167, 167, 0.2);">
      © 2021 Copyright:
      <a class="text-light" href="#">Sebastian Gonzalo Rios</a>
    </div>
    <!-- Copyright -->
</footer>

4_flask_app_mio/flask_app/my_app/templates/fragment/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="#">Flask</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
	  <span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarNavDropdown">
	  <ul class="navbar-nav mr-auto">
	   {% if current_user.username %}
		<li class="nav-item active">
		  <a class="nav-link" href="{{url_for('product.index')}}">Inicio <span class="sr-only">(current)</span></a>
		</li>
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			CRUD
		  </a>
		  <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			<a class="dropdown-item" href="{{url_for('product.index')}}">Productos</a>
			<a class="dropdown-item" href="{{url_for('category.index')}}">Categorías</a>
		  </div>
		</li>
	   {% endif %}
	  </ul>

	  <ul class="navbar-nav">
		{% if not current_user.username %}
			<li class="nav-item">
				<a class="nav-link" href="{{url_for('fauth.login')}}">Login </a>
			</li>
		{% endif %}
	   {% if current_user.username %}
		<li class="nav-item dropdown">
		  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			Hola: {{ current_user.username }}
		  </a>
		  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
			<a class="dropdown-item" href="#">Perfil </a>
			<a class="dropdown-item" href="{{url_for('fauth.logout')}}">Logout </a>
		  </div>
		</li>
	   {% endif %}
	  </ul>

	</div>
  </nav>

4_flask_app_mio/flask_app/my_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Esto lo hacemos para que no se agregue el error del favicon.ico -->
    <link rel="shortcut icon" href="#">

    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='product/css/style.custom.css') }}">

    <title>CRUD</title>
</head>
<body>
    {% include 'fragment/_nav.html' %}
    <div class="container">
        {% block container %}
        {% endblock %}
    </div>
    {% include 'fragment/_footer.html' %}
    
    <script src="{{ url_for('static', filename='global/js/jquery-3.5.1.slim.min.js') }}"></script>
    <script src="{{ url_for('static', filename='global/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='product/js/main.js') }}"></script>
</body>
</html>

4_flask_app_mio/flask_app/my_app/templates/layout/testeo.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Title</title>
    </head>
    <body>
        <header>
            <h3 class="text-center"></h3>
        </header>
        <div class="container">
        </div>

    </body>
</html>

4_flask_app_mio/flask_app/my_app/templates/macro/_pagination.html
{% macro m_pagination(pagination, model) %}
    <div class="container">
        <div class="row">
            <div class="col-3 py-2">
                <p style="">Mostramos los registros</p>
            </div>
            <div class="col-9">
                <nav aria-label="Page navigation example">
                    <ul class="pagination">
                        {% if pagination.has_prev %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for(model, page=pagination.prev_num) }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a href="#" class="page-link" aria-disabled="true">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}
                        {%- for page in pagination.iter_pages() %}
                            {% if page != pagination.page %}
                                <li class="page-item"><a class="page-link" href="{{ url_for(model, page=page) }}">{{ page }}</a></li>
                            {% else %}
                                <li class="page-item active" aria-current="page">
                                    <a class="page-link" href="#">{{ page }}</a>
                                </li>
                            {% endif %}
                        {%- endfor %}
                        {% if pagination.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="{{ url_for(model, page=pagination.next_num) }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a href="#" class="page-link" aria-disabled="true">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{%- endmacro %}

4_flask_app_mio/flask_app/my_app/templates/product/_form.html
<div class="form-group">
    {{ form.name.label }} 
    {{ form.name(class="form-control", placeholder="Nombre Producto") }}
</div>
<div class="form-group">
    {{ form.price.label }}
    {{ form.price(class="form-control", placeholder="Precio Producto") }}
</div>
<div class="form-group">
    {{ form.category_id.label }}
    {{ form.category_id(class="form-control", placeholder="Categoría Producto") }}
</div>

4_flask_app_mio/flask_app/my_app/templates/product/_message.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success fade show mt-3" id="alert-message">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

4_flask_app_mio/flask_app/my_app/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    {% include 'product/_message.html' %}

    <form action="{{ url_for('product.create') }}" method="post">
        {% include 'product/_form.html' %}
        <input class="btn btn-success" type="submit" value="Enviar">
    </form>
    <br>
{% endblock %}

4_flask_app_mio/flask_app/my_app/templates/product/filter.html
<h3>{{product['name']}}</h3>

<p>{{product['category']}}</p>
<p>$ {{product['price']}}</p>

<p>{{product['price']|default('Sin precio', True)}}</p>

{{ "<h1>Filtro safe: Hola Mundo</h1>" | safe }}

<p>{{ "Filtro truncate: Esto es la descripcion de un producto bastante chulo" | truncate(33) }}</p>
<p>{{ "Filtro truncate: Esto es la descripcion de un producto bastante chulo" | count }}</p>
<p>Filtro float: {{70 | float}}</p>
<p>Filtro int: {{"70" | int}}</p>
<p>Filtro round: {{3.1415926535 | round(3) }}</p>
<p>Filtro join: {{["iPhone","iPad"] | join(", ")}}</p>
<p>Filtro length: {{["iPhone","iPad"] | length}}</p>
<p>{{ {'ofer': False, 'price' : 50.5, 'k' : 45} | tojson}}</p>

<p>Filtro gobal custom {{product['price'] | mydouble}}</p>

<p>Filtro local custom {{product | iva}}</p>

4_flask_app_mio/flask_app/my_app/templates/product/index.html
{% extends 'layout/base.html' %}
{% from 'macro/_pagination.html' import m_pagination %}

{% block container %}
    {% include 'product/_message.html' %}
    <br>
    <div>
        <a class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="top" title="Agregar un producto en la BD" href="{{ url_for('product.create') }}"><i class="fa fa-plus"></i> Agregar Producto</a>
    </div>
    <br>
    <div class="list-product">
        {% for product in products.items %}
            <div class="jumbotron pb-2 pt-3 {{ loop.cycle('odd', 'even') }}">
                <h3>
                    <a href="{{ url_for('product.show', id=product['id'])}}">
                        {{product['name']}}
                    </a>
                </h3>
                <h5>{{ product['category'].name }}</h5>
                <a class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Editar Producto" href="{{ url_for('product.update', id=product['id'])}}"><i class="fa fa-edit"></i></a>
                <button data-toggle="modal" data-target="#deleteModal" data-name="{{ product['name'] }}" data-id="{{ product['id'] }}" class="btn btn-danger btn-sm" href="{{ url_for('product.delete', id=product['id'])}}"><i class="fa fa-trash" data-toggle="tooltip" data-placement="top" title="Eliminar {{ product['name'] }}"></i></button>
            </div>
        {% endfor %}
    </div>

    {{ m_pagination(products, 'product.index') }}
    
    <!-- Modal para confirmar la eliminación de los productos -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Borrar: <span></span></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                ¿Seguro que desea borrar el registro seleccionado?
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
              <a href="#" id="deleteProduct" class="btn btn-danger">Borrar</a>
            </div>
          </div>
        </div>
      </div>

    <script>
        window.onload = function(){
            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget) // Button that triggered the modal
                var id = button.data('id') // Extract info from data-* attributes 
                var name = button.data('name') // Extract info from data-* attributes
                // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
                // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
                var modal = $(this)
                modal.find('.modal-title span').text(name)

                $("#deleteProduct").attr("href", "/product-delete/" + id)
            })
        }
    </script>
{% endblock %}

4_flask_app_mio/flask_app/my_app/templates/product/show.html
<h3>{{product['name']}}</h3>

<p>$ {{product['price']}}</p>

{% if product['price'] > 50 %}
    <p>Precio Regular</p>
{% else %}
    <p>Precio de Oferta!!!</p>
{% endif %}

4_flask_app_mio/flask_app/my_app/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    {% include 'product/_message.html' %}
    
    <form action="{{ url_for('product.update', id=product.id) }}" method="post">
        {% include 'product/_form.html' %}
        <input class="btn btn-success" type="submit" value="Actualizar">
    </form>
    <br>
{% endblock %}