4_flask_app/flask_app/my_app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

#app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
#app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+pymysql://root:root@localhost:3306/pyalmacen"
app.config.from_object('configuration.DevelopmentConfig')
db =SQLAlchemy(app)

from my_app.product.views import product
#importar las vistas
app.register_blueprint(product)

db.create_all()


@app.template_filter('mydouble')
def mydouble_filter(n:float):
    return n*2

4_flask_app/flask_app/my_app/product/__init__.py
#sin contenido
#necesario para crear una app modular en python

4_flask_app/flask_app/my_app/product/views.py
#from my_app import app
from flask import Blueprint, render_template, request, redirect, url_for, flash, get_flashed_messages
from werkzeug.exceptions import abort
from sqlalchemy.sql.expression import not_,or_

from my_app import db
from my_app.product.model.products import PRODUCTS
from my_app.product.model.product import Product
from my_app.product.model.product import ProductForm


product = Blueprint('product',__name__)

@product.route('/product')
@product.route('/product/<int:page>')
def index(page=1):
   return render_template('product/index.html', products=Product.query.paginate(page,5))

@product.route('/product-show/<int:id>')
def show(id):
   product = Product.query.get_or_404(id)   
   return render_template('product/show.html', product=product)

@product.route('/product-delete/<int:id>')
def delete(id):
   product = Product.query.get_or_404(id)   

   db.session.delete(product)
   db.session.commit()
   flash("Producto eliminado con éxito")

   return redirect(url_for('product.index'))

@product.route('/product-create', methods=('GET', 'POST'))
def create():
   form = ProductForm(meta={'csrf':False})
   if form.validate_on_submit():
      #crear producto
      p = Product(request.form['name'],request.form['price'])
      db.session.add(p)
      db.session.commit()
      flash("Producto creado con éxito")
      return redirect(url_for('product.create'))

   if form.errors:
      flash(form.errors,'danger')

   return render_template('product/create.html',form=form)


@product.route('/product-update/<int:id>', methods=['GET','POST'])
def update(id):
   product = Product.query.get_or_404(id)   
   form = ProductForm(meta={'csrf':False})

   if request.method == 'GET':
      form.name.data = product.name
      form.price.data = product.price

   if form.validate_on_submit():
      #actualizar producto
      product.name = form.name.data
      product.price = form.price.data

      db.session.add(product)
      db.session.commit()
      flash("Producto actualizado con éxito")
      return redirect(url_for('product.update',id=product.id))

      if form.errors:
         flash(form.errors,'danger')

   return render_template('product/update.html',product=product, form=form)
   

@product.route('/test')
def test():
   # consultar
   #p = Product.query.limit(2).all()
   #p = Product.query.limit(2).first()
   #p = Product.query.order_by(Product.id.desc()).all()
   #p = Product.query.get({"id":"P1"})
   #p = Product.query.filter_by(name = "P1").first()
   #p = Product.query.filter(Product.id > 1).all()
   #p = Product.query.filter_by(name = "P1", id=2).first()
   #p = Product.query.filter(Product.name.like('%P%')).all()
   #p = Product.query.filter(not_(Product.id > 1)).all()
   #p = Product.query.filter(or_(Product.id > 1, Product.name=="P1")).all()
   #print(p)

   #crear
   #p = Product("P5",60.8)
   #db.session.add(p)
   #db.session.commit()
   #Product.add(p)

   #actualizar
   #p = Product.query.filter_by(name = "P1", id=1).first()
   #p.name = "UP1"
   #db.session.add(p)
   #db.session.commit()

      #eliminar
   p = Product.query.filter_by(id=1).first()
   db.session.delete(p)
   db.session.commit()
   
   return "Flask"

@product.route('/filter/<int:id>')
def filter(id):
   product = PRODUCTS.get(id)
   return render_template('product/filter.html', product=product)


@product.app_template_filter('iva')
def iva_filter(product):
   if product["price"]:
      return product["price"] * .20 + product["price"]
   return "Sin precio"

4_flask_app/flask_app/my_app/templates/layout/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>CRUD</title>
</head>
<body>
    <header>Header de la app</header>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

    {% block container %}
    {% endblock %}

    <footer>Footer</footer>
</body>
</html>

4_flask_app/flask_app/my_app/templates/product/_form.html
{{ form.name.label }} {{ form.name }}
{{ form.price.label }} {{ form.price }}

4_flask_app/flask_app/my_app/templates/product/create.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.create') }}" method="POST">
        {% include 'product/_form.html' %}

        <input type="submit" value="Enviar">
    </form>
{% endblock %}

4_flask_app/flask_app/my_app/templates/product/filter.html
<h3>{{ product['name'] }}</h3>

<p>{{ product['category'] }}</p>
<p>$ {{ product['price'] }}</p>

<p>Filtro default: {{ product['price'] | default('Sin precio', True) }}</p>

{{ "<h1>Filtro Safe: Hola Mundo</h1>" | safe }}

<p>{{ "Filtro truncate: Esto es la descripción de un producto bastante chulo" | truncate(23) }}</p>
<p>{{ "Filtro count: Esto es la descripción de un producto bastante chulo" | count }}</p>
<p>Filtro float: {{ "70.7" | float }}</p>
<p>Filtro int: {{ 70.7 | int }}</p>
<p>Filtro round: {{ 3.1415926535 | round(3) }}</p>
<p>Filtro join: {{ ["iPhone","iPad"] | join(", ") }}</p>
<p>Filtro length: {{ ["iPhone","iPad"] | length }}</p>
<p>{{ {'offer': False, 'price': 50.5, 'k': 45} | tojson }}</p>

<p>Filtro global custom {{ 50 | mydouble }}</p>
<p>Filtro local custom {{ product | iva }}</p>

4_flask_app/flask_app/my_app/templates/product/index.html
{% extends 'layout/base.html' %}

{% block container %}
    {% for product in products.items %}
        <div>
            <a href="{{ url_for('product.show', id=product['id']) }}">{{ product['name'] }}</a>

            <a href="{{ url_for('product.update', id=product['id']) }}">Editar</a>

            <a href="{{ url_for('product.delete', id=product['id']) }}">Eliminar</a>
        </div>
    {% endfor %}

    <div class=pagination>
        {%- for page in products.iter_pages() %}
          
            {% if page != products.page %}
              <a href="{{ url_for('product.index', page=page) }}">{{ page }}</a>
            {% else %}
              <strong>{{ page }}</strong>
            {% endif %}
        {%- endfor %}
    </div>

{% endblock %}

4_flask_app/flask_app/my_app/templates/product/show.html
{% extends 'layout/base.html' %}

{% block container %}
<h3>{{ product['name'] }}</h3>

<p>{{ product['category'] }}</p>
<p>$ {{ product['price'] }}</p>

{% if product['price'] >= 1000 %}
 <p>Precio Regular</p>
{% else %}
<p>Precio oferta!!</p>
{% endif %}

{% endblock %}

4_flask_app/flask_app/my_app/templates/product/update.html
{% extends 'layout/base.html' %}

{% block container %}
    <form action="{{ url_for('product.update',id=product.id) }}" method="POST">
        {% include 'product/_form.html' %}
        <input type="submit" value="Actualizar">
    </form>
{% endblock %}